// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (firm_id, name, industry, primary_contact_email)
VALUES ($1, $2, $3, $4)
RETURNING id, firm_id, name, industry, primary_contact_email, created_at
`

type CreateClientParams struct {
	FirmID              uuid.UUID   `json:"firm_id"`
	Name                string      `json:"name"`
	Industry            pgtype.Text `json:"industry"`
	PrimaryContactEmail pgtype.Text `json:"primary_contact_email"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.FirmID,
		arg.Name,
		arg.Industry,
		arg.PrimaryContactEmail,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.FirmID,
		&i.Name,
		&i.Industry,
		&i.PrimaryContactEmail,
		&i.CreatedAt,
	)
	return i, err
}

const getClientByID = `-- name: GetClientByID :one
SELECT id, firm_id, name, industry, primary_contact_email, created_at FROM clients WHERE id = $1
`

func (q *Queries) GetClientByID(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.FirmID,
		&i.Name,
		&i.Industry,
		&i.PrimaryContactEmail,
		&i.CreatedAt,
	)
	return i, err
}

const listClientsByFirmID = `-- name: ListClientsByFirmID :many
SELECT id, firm_id, name, industry, primary_contact_email, created_at FROM clients
WHERE firm_id = $1
ORDER BY name ASC
LIMIT $2 OFFSET $3
`

type ListClientsByFirmIDParams struct {
	FirmID uuid.UUID `json:"firm_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListClientsByFirmID(ctx context.Context, arg ListClientsByFirmIDParams) ([]Client, error) {
	rows, err := q.db.Query(ctx, listClientsByFirmID, arg.FirmID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.FirmID,
			&i.Name,
			&i.Industry,
			&i.PrimaryContactEmail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients
SET name = COALESCE($2, name),
    industry = COALESCE($3, industry),
    primary_contact_email = COALESCE($4, primary_contact_email)
WHERE id = $1
RETURNING id, firm_id, name, industry, primary_contact_email, created_at
`

type UpdateClientParams struct {
	ID                  uuid.UUID   `json:"id"`
	Name                pgtype.Text `json:"name"`
	Industry            pgtype.Text `json:"industry"`
	PrimaryContactEmail pgtype.Text `json:"primary_contact_email"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClient,
		arg.ID,
		arg.Name,
		arg.Industry,
		arg.PrimaryContactEmail,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.FirmID,
		&i.Name,
		&i.Industry,
		&i.PrimaryContactEmail,
		&i.CreatedAt,
	)
	return i, err
}
