// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: firms.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFirm = `-- name: CreateFirm :one
INSERT INTO firms (name, slug, billing_contact_email, country, staff_count_range, primary_audit_types)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, slug, logo_url, timezone, billing_contact_email, subscription_tier, country, staff_count_range, primary_audit_types, settings, created_at
`

type CreateFirmParams struct {
	Name                string      `json:"name"`
	Slug                string      `json:"slug"`
	BillingContactEmail string      `json:"billing_contact_email"`
	Country             string      `json:"country"`
	StaffCountRange     pgtype.Text `json:"staff_count_range"`
	PrimaryAuditTypes   []byte      `json:"primary_audit_types"`
}

func (q *Queries) CreateFirm(ctx context.Context, arg CreateFirmParams) (Firm, error) {
	row := q.db.QueryRow(ctx, createFirm,
		arg.Name,
		arg.Slug,
		arg.BillingContactEmail,
		arg.Country,
		arg.StaffCountRange,
		arg.PrimaryAuditTypes,
	)
	var i Firm
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.Timezone,
		&i.BillingContactEmail,
		&i.SubscriptionTier,
		&i.Country,
		&i.StaffCountRange,
		&i.PrimaryAuditTypes,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}

const getFirmByID = `-- name: GetFirmByID :one
SELECT id, name, slug, logo_url, timezone, billing_contact_email, subscription_tier, country, staff_count_range, primary_audit_types, settings, created_at FROM firms WHERE id = $1
`

func (q *Queries) GetFirmByID(ctx context.Context, id uuid.UUID) (Firm, error) {
	row := q.db.QueryRow(ctx, getFirmByID, id)
	var i Firm
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.Timezone,
		&i.BillingContactEmail,
		&i.SubscriptionTier,
		&i.Country,
		&i.StaffCountRange,
		&i.PrimaryAuditTypes,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}

const updateFirm = `-- name: UpdateFirm :one
UPDATE firms
SET name = COALESCE($2, name),
    logo_url = COALESCE($3, logo_url),
    timezone = COALESCE($4, timezone),
    billing_contact_email = COALESCE($5, billing_contact_email),
    settings = COALESCE($6, settings)
WHERE id = $1
RETURNING id, name, slug, logo_url, timezone, billing_contact_email, subscription_tier, country, staff_count_range, primary_audit_types, settings, created_at
`

type UpdateFirmParams struct {
	ID                  uuid.UUID   `json:"id"`
	Name                pgtype.Text `json:"name"`
	LogoUrl             pgtype.Text `json:"logo_url"`
	Timezone            pgtype.Text `json:"timezone"`
	BillingContactEmail pgtype.Text `json:"billing_contact_email"`
	Settings            []byte      `json:"settings"`
}

func (q *Queries) UpdateFirm(ctx context.Context, arg UpdateFirmParams) (Firm, error) {
	row := q.db.QueryRow(ctx, updateFirm,
		arg.ID,
		arg.Name,
		arg.LogoUrl,
		arg.Timezone,
		arg.BillingContactEmail,
		arg.Settings,
	)
	var i Firm
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.Timezone,
		&i.BillingContactEmail,
		&i.SubscriptionTier,
		&i.Country,
		&i.StaffCountRange,
		&i.PrimaryAuditTypes,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}
