// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invitations.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acceptInvitation = `-- name: AcceptInvitation :one
UPDATE invitations
SET status = 'Accepted', accepted_at = now()
WHERE id = $1 AND status = 'Sent'
RETURNING id, firm_id, email, assigned_role, token_hash, status, expires_at, reminder_sent_at, invited_by_id, accepted_at, created_at
`

func (q *Queries) AcceptInvitation(ctx context.Context, id uuid.UUID) (Invitation, error) {
	row := q.db.QueryRow(ctx, acceptInvitation, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.FirmID,
		&i.Email,
		&i.AssignedRole,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.ReminderSentAt,
		&i.InvitedByID,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const cancelInvitation = `-- name: CancelInvitation :exec
UPDATE invitations SET status = 'Expired' WHERE id = $1 AND status = 'Sent'
`

func (q *Queries) CancelInvitation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancelInvitation, id)
	return err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (firm_id, email, assigned_role, token_hash, expires_at, invited_by_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, firm_id, email, assigned_role, token_hash, status, expires_at, reminder_sent_at, invited_by_id, accepted_at, created_at
`

type CreateInvitationParams struct {
	FirmID       uuid.UUID `json:"firm_id"`
	Email        string    `json:"email"`
	AssignedRole UserRole  `json:"assigned_role"`
	TokenHash    string    `json:"token_hash"`
	ExpiresAt    time.Time `json:"expires_at"`
	InvitedByID  uuid.UUID `json:"invited_by_id"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.FirmID,
		arg.Email,
		arg.AssignedRole,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.InvitedByID,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.FirmID,
		&i.Email,
		&i.AssignedRole,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.ReminderSentAt,
		&i.InvitedByID,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitationByTokenHash = `-- name: GetInvitationByTokenHash :one
SELECT id, firm_id, email, assigned_role, token_hash, status, expires_at, reminder_sent_at, invited_by_id, accepted_at, created_at FROM invitations WHERE token_hash = $1
`

func (q *Queries) GetInvitationByTokenHash(ctx context.Context, tokenHash string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByTokenHash, tokenHash)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.FirmID,
		&i.Email,
		&i.AssignedRole,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.ReminderSentAt,
		&i.InvitedByID,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listInvitationsByFirmID = `-- name: ListInvitationsByFirmID :many
SELECT id, firm_id, email, assigned_role, token_hash, status, expires_at, reminder_sent_at, invited_by_id, accepted_at, created_at FROM invitations
WHERE firm_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListInvitationsByFirmIDParams struct {
	FirmID uuid.UUID `json:"firm_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListInvitationsByFirmID(ctx context.Context, arg ListInvitationsByFirmIDParams) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listInvitationsByFirmID, arg.FirmID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invitation{}
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.FirmID,
			&i.Email,
			&i.AssignedRole,
			&i.TokenHash,
			&i.Status,
			&i.ExpiresAt,
			&i.ReminderSentAt,
			&i.InvitedByID,
			&i.AcceptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
