// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthMethod string

const (
	AuthMethodPassword AuthMethod = "Password"
	AuthMethodOAuth    AuthMethod = "OAuth"
	AuthMethodSAML     AuthMethod = "SAML"
)

func (e *AuthMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthMethod(s)
	case string:
		*e = AuthMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthMethod: %T", src)
	}
	return nil
}

type NullAuthMethod struct {
	AuthMethod AuthMethod `json:"auth_method"`
	Valid      bool       `json:"valid"` // Valid is true if AuthMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthMethod) Scan(value interface{}) error {
	if value == nil {
		ns.AuthMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthMethod), nil
}

type InvitationStatus string

const (
	InvitationStatusSent     InvitationStatus = "Sent"
	InvitationStatusAccepted InvitationStatus = "Accepted"
	InvitationStatusExpired  InvitationStatus = "Expired"
)

func (e *InvitationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvitationStatus(s)
	case string:
		*e = InvitationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InvitationStatus: %T", src)
	}
	return nil
}

type NullInvitationStatus struct {
	InvitationStatus InvitationStatus `json:"invitation_status"`
	Valid            bool             `json:"valid"` // Valid is true if InvitationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvitationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InvitationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvitationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvitationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvitationStatus), nil
}

type NotificationFrequency string

const (
	NotificationFrequencyRealTime NotificationFrequency = "RealTime"
	NotificationFrequencyDaily    NotificationFrequency = "Daily"
	NotificationFrequencyWeekly   NotificationFrequency = "Weekly"
)

func (e *NotificationFrequency) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationFrequency(s)
	case string:
		*e = NotificationFrequency(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationFrequency: %T", src)
	}
	return nil
}

type NullNotificationFrequency struct {
	NotificationFrequency NotificationFrequency `json:"notification_frequency"`
	Valid                 bool                  `json:"valid"` // Valid is true if NotificationFrequency is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationFrequency) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationFrequency, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationFrequency.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationFrequency) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationFrequency), nil
}

type UserRole string

const (
	UserRoleFirmAdmin   UserRole = "FirmAdmin"
	UserRolePartner     UserRole = "Partner"
	UserRoleManager     UserRole = "Manager"
	UserRoleStaff       UserRole = "Staff"
	UserRoleEQReviewer  UserRole = "EQReviewer"
	UserRoleClientAdmin UserRole = "ClientAdmin"
	UserRoleClientUser  UserRole = "ClientUser"
	UserRoleViewOnly    UserRole = "ViewOnly"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Client struct {
	ID                  uuid.UUID   `json:"id"`
	FirmID              uuid.UUID   `json:"firm_id"`
	Name                string      `json:"name"`
	Industry            pgtype.Text `json:"industry"`
	PrimaryContactEmail pgtype.Text `json:"primary_contact_email"`
	CreatedAt           time.Time   `json:"created_at"`
}

type Firm struct {
	ID                  uuid.UUID       `json:"id"`
	Name                string          `json:"name"`
	Slug                string          `json:"slug"`
	LogoUrl             pgtype.Text     `json:"logo_url"`
	Timezone            string          `json:"timezone"`
	BillingContactEmail string          `json:"billing_contact_email"`
	SubscriptionTier    string          `json:"subscription_tier"`
	Country             string          `json:"country"`
	StaffCountRange     pgtype.Text     `json:"staff_count_range"`
	PrimaryAuditTypes   []byte          `json:"primary_audit_types"`
	Settings            json.RawMessage `json:"settings"`
	CreatedAt           time.Time       `json:"created_at"`
}

type Invitation struct {
	ID             uuid.UUID          `json:"id"`
	FirmID         uuid.UUID          `json:"firm_id"`
	Email          string             `json:"email"`
	AssignedRole   UserRole           `json:"assigned_role"`
	TokenHash      string             `json:"token_hash"`
	Status         InvitationStatus   `json:"status"`
	ExpiresAt      time.Time          `json:"expires_at"`
	ReminderSentAt pgtype.Timestamptz `json:"reminder_sent_at"`
	InvitedByID    uuid.UUID          `json:"invited_by_id"`
	AcceptedAt     pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt      time.Time          `json:"created_at"`
}

type User struct {
	ID                    uuid.UUID             `json:"id"`
	FirmID                pgtype.UUID           `json:"firm_id"`
	ClientID              pgtype.UUID           `json:"client_id"`
	Email                 string                `json:"email"`
	DisplayName           string                `json:"display_name"`
	Role                  UserRole              `json:"role"`
	AuthMethod            AuthMethod            `json:"auth_method"`
	PasswordHash          pgtype.Text           `json:"password_hash"`
	NotificationFrequency NotificationFrequency `json:"notification_frequency"`
	TourCompleted         bool                  `json:"tour_completed"`
	IsActive              bool                  `json:"is_active"`
	CreatedAt             time.Time             `json:"created_at"`
}
