// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (firm_id, email, display_name, role, auth_method, password_hash, notification_frequency)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, firm_id, client_id, email, display_name, role, auth_method, password_hash, notification_frequency, tour_completed, is_active, created_at
`

type CreateUserParams struct {
	FirmID                pgtype.UUID           `json:"firm_id"`
	Email                 string                `json:"email"`
	DisplayName           string                `json:"display_name"`
	Role                  UserRole              `json:"role"`
	AuthMethod            AuthMethod            `json:"auth_method"`
	PasswordHash          pgtype.Text           `json:"password_hash"`
	NotificationFrequency NotificationFrequency `json:"notification_frequency"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirmID,
		arg.Email,
		arg.DisplayName,
		arg.Role,
		arg.AuthMethod,
		arg.PasswordHash,
		arg.NotificationFrequency,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirmID,
		&i.ClientID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.AuthMethod,
		&i.PasswordHash,
		&i.NotificationFrequency,
		&i.TourCompleted,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users SET is_active = false WHERE id = $1
`

func (q *Queries) DeactivateUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, firm_id, client_id, email, display_name, role, auth_method, password_hash, notification_frequency, tour_completed, is_active, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirmID,
		&i.ClientID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.AuthMethod,
		&i.PasswordHash,
		&i.NotificationFrequency,
		&i.TourCompleted,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, firm_id, client_id, email, display_name, role, auth_method, password_hash, notification_frequency, tour_completed, is_active, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirmID,
		&i.ClientID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.AuthMethod,
		&i.PasswordHash,
		&i.NotificationFrequency,
		&i.TourCompleted,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listUsersByFirmID = `-- name: ListUsersByFirmID :many
SELECT id, firm_id, client_id, email, display_name, role, auth_method, password_hash, notification_frequency, tour_completed, is_active, created_at FROM users
WHERE firm_id = $1 AND is_active = true
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUsersByFirmIDParams struct {
	FirmID pgtype.UUID `json:"firm_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListUsersByFirmID(ctx context.Context, arg ListUsersByFirmIDParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByFirmID, arg.FirmID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FirmID,
			&i.ClientID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
			&i.AuthMethod,
			&i.PasswordHash,
			&i.NotificationFrequency,
			&i.TourCompleted,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET role = COALESCE($2, role),
    display_name = COALESCE($3, display_name),
    notification_frequency = COALESCE($4, notification_frequency),
    is_active = COALESCE($5, is_active)
WHERE id = $1
RETURNING id, firm_id, client_id, email, display_name, role, auth_method, password_hash, notification_frequency, tour_completed, is_active, created_at
`

type UpdateUserParams struct {
	ID                    uuid.UUID                 `json:"id"`
	Role                  NullUserRole              `json:"role"`
	DisplayName           pgtype.Text               `json:"display_name"`
	NotificationFrequency NullNotificationFrequency `json:"notification_frequency"`
	IsActive              pgtype.Bool               `json:"is_active"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Role,
		arg.DisplayName,
		arg.NotificationFrequency,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirmID,
		&i.ClientID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.AuthMethod,
		&i.PasswordHash,
		&i.NotificationFrequency,
		&i.TourCompleted,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
